# Netlify configuration file
[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.x"

[[redirects]]
  # Redirect API requests to Netlify functions
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
# Redirect all unmatched routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200.html"
  status = 200